services:
  manico_backend:
    container_name: manico_backend
    image: backend-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    env_file:
    - .env
