name: Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Optional: Set up Docker buildx for better build performance
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    
    # SSH into VPS and deploy
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          # Navigate to your project directory
          cd /root/Manio-Server

          
          # Pull the latest code
          git pull origin main
          
          # Stop existing containers
          docker-compose down
          
          # Pull the latest images (if using external registry)
          # docker-compose pull
          
          # Rebuild and start containers
          docker-compose up -d --build
          
          # Optional: Prune old images and volumes to save space
          docker image prune -f
          docker volume prune -f
